# Generated by Django 6.0.4 on 2026-04-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
